[user]
email = "boyswan@email.com"
name = "boyswan"


[aliases]
b = ["bookmark"]
n = ["new"]

[ui]
paginate = "never"    # UPDATED: This correctly disables the pager
default-command = "log --reversed"
